Summary:	An SNMP library implementation based on glib and gnet
Name:		gsnmp
Version:	0.3.0
Release:	0.1
License:	GPL v2
Group:		Networking
URL:		http://www.ibr.cs.tu-bs.de/projects/scli/
Source0:	ftp://ftp.ibr.cs.tu-bs.de/local/gsnmp/%{name}-%{version}.tar.gz
# Source0-md5:	466699c11b70e18a04d51388b8f89f1c
BuildRequires:	autoconf >= 2.59
BuildRequires:	glib2-devel >= 2.0.0
BuildRequires:	gnet-devel >= 2.0.4
BuildRequires:	libxml2-devel
BuildRequires:	ncurses-devel
BuildRequires:	pkgconfig >= 0.16
BuildRequires:	readline-devel

%define         skip_post_check_so	libgsnmp.so.0.0.0

%description
GNET-SNMP is an SNMP library implementation based on glib and gnet.
This library has been developed as part of the scli package (an SNMP
command line interface). Some examples demonstrating the API can be
found in the examples directory. Some examples use stub files
generated by the smidump MIB compiler, which is part of the libsmi
package.

%package lib
Summary:	A library of functions for the snmp protocol
Group:		Libraries

%description lib
This package contains the library needed to run programs dynamically
linked with libgsnmp.

%package devel
Summary:	Development tools for the snmp protocol
Group:		Development/Libraries
Requires:	%{name} = %{version}-%{release}
Requires:	glib2-devel

%description devel
This package contains the header files and libraries necessary for
developing programs using libgsnmp.

%prep
%setup -q

%build
%{__autoconf}
%configure

%{__make}

%install
rm -rf $RPM_BUILD_ROOT
%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

%{__rm} -f $RPM_BUILD_ROOT%{_libdir}/libgsnmp.a

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc AUTHORS ChangeLog NEWS README
%attr(755,root,root) %{_bindir}/gsnmp-get
%{_mandir}/man1/gsnmp-get.*

%files lib
%defattr(644,root,root,755)
%attr(755,root,root) %{_libdir}/libgsnmp.so.*

%files devel
%defattr(644,root,root,755)
%{_includedir}/%{name}
%{_libdir}/libgsnmp.la
%attr(755,root,root) %{_libdir}/libgsnmp.so
%{_pkgconfigdir}/%{name}.pc
%{_aclocaldir}/%{name}.m4
